name: pygsflow
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pyshp
  - pycrs
  - matplotlib
  - coverage
  - appdirs
  - requests
  - affine
  - scipy
  - pandas
  - netcdf4
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely>=1.8
  - pycrs
  - geos>=3.9.1
  - rasterstats